# ???????Python?????
server.port=8000

# ????????????????????&???????
spring.datasource.url=jdbc:mysql://localhost:3306/score_manage?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=456123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.scoremanage.model